name: Cypress Tests

on:
  push:
    branches: [main]

  pull_request_target:
    types: [labeled, opened, synchronize, reopened]
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Packages
        run: |
          npm install --legacy-peer-deps

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install-command: |
            npm install --legacy-peer-deps
          start: npm start
          wait-on: "http://localhost:3000"
          browser: chrome
        env:
          # pass GitHub token to detect new build vs re-run build
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
